blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/miladrezanezhad/sir_simulator/blob/main/README.md
    about: Check the documentation first
  - name: 💬 Discussions
    url: https://github.com/miladrezanezhad/sir_simulator/discussions
    about: Ask questions and discuss ideas
  - name: 📧 Email Maintainer
    url: mailto:miladvf2014@gmail.com
    about: Contact the maintainer directly
